apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config

data:
  SERVER_PORT: "8080" 
  DB_HOST: order-db-0.order-db-service.default.svc.cluster.local 
  DB_PORT: "5432" 
  DB_USER: postgres
  DB_NAME: postgres 
  BOOK_SERVICE_URL: http://book-service
  USER_SERVICE_URL: http://user-service
  SERVICE_TIMEOUT: 10s
  READ_TIMEOUT: 15s
  WRITE_TIMEOUT: 15s
  IDLE_TIMEOUT: 60s
  LOG_LEVEL: info
  LOG_FORMAT: json