apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service-deploy

spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
      - name: book-service-container
        image: spaul76/book-service:{{ .Values.image_tag }}
        envFrom:
        - configMapRef:
            name: book-config
        - secretRef:
            name: book-secret
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 150Mi
          limits:
            cpu: 300m
            memory: 400Mi 
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
